# Site settings
title: SIGCSE 2017

email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Website for the SIGCSE 2017 annual technical symposium.
  Concerns may be directed to jadudm@berea.edu.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://localhost"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - _venv
